name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.2xx
          dotnet-quality: 'nightly'

      - name: Build the app
        run: dotnet publish -check -bl

      - name: Upload binlog
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: msbuild.binlog
          if-no-files-found: error
          overwrite: true
