name: Build project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.2xx
          dotnet-quality: 'daily'

      - name: Build the app
        run: dotnet publish -bl /check

      - name: Redact binlogs
        if: always()
        run: |
         echo "Installing Binlog redactor CLI..."
         dotnet tool install binlogtool --global
         binlogtool redact -p:Contoso
      
      - name: Upload nonredacted binlog
        uses: actions/upload-artifact@v4
        if: always()
        with:
           name: logs
           path: msbuild.binlog
           if-no-files-found: error
           overwrite: true

      - name: Upload redacted binlog
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: logs
          path: msbuild.redacted.binlog
          if-no-files-found: error
          overwrite: true